# Generated by Django 4.0.3 on 2022-03-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('date_added',), 'verbose_name': 'ตระกร้าสินค้า', 'verbose_name_plural': 'ตระกร้าสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'รายการสินค้าในตระกร้า', 'verbose_name_plural': 'รายการสินค้าในตระกร้า'},
        ),
    ]
